language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install

script:
  - npm run build
  - npm run docs:build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  repo: xapp-ui/xapp-ui.github.io
  keep_history: true
  target-branch: master
  on:
    branch: master
